export const errorMessage = {
    ACCESS_TOKEN_INVALID: 'ACCESS TOKEN INVALID',
    REFRESH_TOKEN_INVALID: 'REFRESH TOKEN INVALID',
    NO_SIGN_IN: 'ACCESS TOKEN IS NULL',
    NO_ENV_FILE: 'ENV FILE IS NOT FOUND',
} as const;
